#!/bin/bash
set -e

if [ "$DOCKERFILE_PATH" == "latest.Dockerfile" ];
then
## Not all bash commands are available. notably grep -o -e options fail!!
VERSION=`sed -n 's|.*R_VERSION:-\([0-9]\.[0-9]\.[0-9]\).*|\1|p' latest.Dockerfile`
echo "Version being built is: $VERSION"

echo "tagging $IMAGE_NAME as $DOCKER_REPO:$VERSION..."
docker tag $IMAGE_NAME $DOCKER_REPO:$VERSION

echo "pushing $DOCKER_REPO:$VERSION to hub..."
docker push $DOCKER_REPO:$VERSION

fi

# docker tag $IMAGE_NAME $DOCKER_REPO:$SOURCE_BRANCH
# docker push $DOCKER_REPO:$SOURCE_BRANCH


